image_tag             = "latest"
instance_type         = "t3.micro"
security_group_id     = "sg-03be953ee3f4eaaf0"
key_pair_name         = "servicelink-key"
instance_profile_name = "servicelink-ec2-ssm-profile"
